backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "Artikel & Publikasi"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Judul Artikel", name: "title", widget: "string"}
      - {label: "Tanggal Rilis", name: "date", widget: "datetime"}
      - {label: "Foto Utama", name: "thumbnail", widget: "image"}
      - {label: "Ringkasan Pendek", name: "description", widget: "text"}
      - {label: "Isi Konten Tulisan", name: "body", widget: "markdown"}
